// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wfcriclidxopnqkwflff.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndmY3JpY2xpZHhvcG5xa3dmbGZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3Mjc1NDgsImV4cCI6MjA3MzMwMzU0OH0.sMhloRNKReOQJ0E_iNCQP2vMAcRMkdmSf2ddtYtZWEQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});